name = "omni-grid-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Enable Cloudflare Default Temporary Domain (*.workers.dev)
workers_dev = true

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "omni-grid-db"
database_id = "1fa1f146-d683-4a10-bb37-a3d46408f038"
migrations_dir = "drizzle"

# R2 Object Storage Bucket Binding
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "omni-grid-uploads"

# KV Throttling & Session Cache
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "919864ee2a794a95a9ee46c18e8bac89"

# ── Environment Variables ──
[vars]
ENVIRONMENT = "production"
BETTER_AUTH_URL = "http://localhost:8787"
BETTER_AUTH_SECRET = "omni_grid_production_super_secret_session_key_2026_pk"
