name = "omni-grid-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

# Enable Cloudflare Default Temporary Domain (*.workers.dev)
workers_dev = true

# ── Environment Variables ──
[vars]
ENVIRONMENT = "production"
BETTER_AUTH_URL = "http://localhost:8787"
BETTER_AUTH_SECRET = "omni_grid_production_super_secret_session_key_2026_pk"
